package Kalkulator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class KalkulatorStandart extends javax.swing.JFrame {
    String angka ="";
double jumlah,angka1,angka2;
int pilih;

    /**
     * Creates new form KalkulatorStandart
     */
    public KalkulatorStandart() {
        initComponents();
        angka ="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        display = new javax.swing.JTextField();
        bil7 = new javax.swing.JButton();
        bil8 = new javax.swing.JButton();
        bil9 = new javax.swing.JButton();
        perkurangan = new javax.swing.JButton();
        bil4 = new javax.swing.JButton();
        bil5 = new javax.swing.JButton();
        bil6 = new javax.swing.JButton();
        penjumlahan = new javax.swing.JButton();
        bil1 = new javax.swing.JButton();
        bil0 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        bil2 = new javax.swing.JButton();
        bil3 = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        perkalian = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        pembagian = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(0, 0, 290, 100);

        bil7.setBackground(new java.awt.Color(51, 51, 51));
        bil7.setForeground(new java.awt.Color(255, 255, 255));
        bil7.setText("7");
        bil7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil7ActionPerformed(evt);
            }
        });
        getContentPane().add(bil7);
        bil7.setBounds(0, 110, 80, 40);

        bil8.setBackground(new java.awt.Color(51, 51, 51));
        bil8.setForeground(new java.awt.Color(255, 255, 255));
        bil8.setText("8");
        bil8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil8ActionPerformed(evt);
            }
        });
        getContentPane().add(bil8);
        bil8.setBounds(80, 110, 80, 40);

        bil9.setBackground(new java.awt.Color(51, 51, 51));
        bil9.setForeground(new java.awt.Color(255, 255, 255));
        bil9.setText("9");
        bil9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil9ActionPerformed(evt);
            }
        });
        getContentPane().add(bil9);
        bil9.setBounds(160, 110, 80, 40);

        perkurangan.setBackground(new java.awt.Color(51, 51, 51));
        perkurangan.setForeground(new java.awt.Color(255, 255, 255));
        perkurangan.setText("-");
        perkurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkuranganActionPerformed(evt);
            }
        });
        getContentPane().add(perkurangan);
        perkurangan.setBounds(240, 110, 50, 30);

        bil4.setBackground(new java.awt.Color(51, 51, 51));
        bil4.setForeground(new java.awt.Color(255, 255, 255));
        bil4.setText("4");
        bil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil4ActionPerformed(evt);
            }
        });
        getContentPane().add(bil4);
        bil4.setBounds(0, 150, 80, 40);

        bil5.setBackground(new java.awt.Color(51, 51, 51));
        bil5.setForeground(new java.awt.Color(255, 255, 255));
        bil5.setText("5");
        bil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil5ActionPerformed(evt);
            }
        });
        getContentPane().add(bil5);
        bil5.setBounds(80, 150, 80, 40);

        bil6.setBackground(new java.awt.Color(51, 51, 51));
        bil6.setForeground(new java.awt.Color(255, 255, 255));
        bil6.setText("6");
        bil6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil6ActionPerformed(evt);
            }
        });
        getContentPane().add(bil6);
        bil6.setBounds(160, 150, 80, 40);

        penjumlahan.setBackground(new java.awt.Color(51, 51, 51));
        penjumlahan.setForeground(new java.awt.Color(255, 255, 255));
        penjumlahan.setText("+");
        penjumlahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjumlahanActionPerformed(evt);
            }
        });
        getContentPane().add(penjumlahan);
        penjumlahan.setBounds(240, 140, 50, 30);

        bil1.setBackground(new java.awt.Color(51, 51, 51));
        bil1.setForeground(new java.awt.Color(255, 255, 255));
        bil1.setText("1");
        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        getContentPane().add(bil1);
        bil1.setBounds(0, 190, 80, 40);

        bil0.setBackground(new java.awt.Color(51, 51, 51));
        bil0.setForeground(new java.awt.Color(255, 255, 255));
        bil0.setText("0");
        bil0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil0ActionPerformed(evt);
            }
        });
        getContentPane().add(bil0);
        bil0.setBounds(-1, 230, 50, 30);

        clear.setBackground(new java.awt.Color(51, 51, 51));
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(90, 230, 60, 30);

        bil2.setBackground(new java.awt.Color(51, 51, 51));
        bil2.setForeground(new java.awt.Color(255, 255, 255));
        bil2.setText("2");
        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });
        getContentPane().add(bil2);
        bil2.setBounds(80, 190, 80, 40);

        bil3.setBackground(new java.awt.Color(51, 51, 51));
        bil3.setForeground(new java.awt.Color(255, 255, 255));
        bil3.setText("3");
        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });
        getContentPane().add(bil3);
        bil3.setBounds(160, 190, 80, 40);

        koma.setBackground(new java.awt.Color(51, 51, 51));
        koma.setForeground(new java.awt.Color(255, 255, 255));
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        getContentPane().add(koma);
        koma.setBounds(50, 230, 40, 30);

        perkalian.setBackground(new java.awt.Color(51, 51, 51));
        perkalian.setForeground(new java.awt.Color(255, 255, 255));
        perkalian.setText("x");
        perkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkalianActionPerformed(evt);
            }
        });
        getContentPane().add(perkalian);
        perkalian.setBounds(240, 170, 50, 30);

        samadengan.setBackground(new java.awt.Color(51, 51, 51));
        samadengan.setForeground(new java.awt.Color(255, 255, 255));
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(samadengan);
        samadengan.setBounds(150, 230, 60, 30);

        pembagian.setBackground(new java.awt.Color(51, 51, 51));
        pembagian.setForeground(new java.awt.Color(255, 255, 255));
        pembagian.setText("/");
        pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianActionPerformed(evt);
            }
        });
        getContentPane().add(pembagian);
        pembagian.setBounds(240, 200, 50, 30);

        delete.setBackground(new java.awt.Color(51, 51, 51));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("<--");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(210, 230, 80, 30);

        setSize(new java.awt.Dimension(308, 299));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
         // fungsi tombol .(koma)
         angka += ".";
         display.setText(angka);
    }//GEN-LAST:event_komaActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
         // fungsi tombol 2
         angka +="2";        
        display.setText(angka);
    }//GEN-LAST:event_bil2ActionPerformed

    private void bil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil5ActionPerformed
         // fungsi tombol 5
         angka +="5";        
        display.setText(angka);
    }//GEN-LAST:event_bil5ActionPerformed

    private void bil8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil8ActionPerformed
        // fungsi tombol 8
         angka +="8";        
        display.setText(angka);
    }//GEN-LAST:event_bil8ActionPerformed

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
         // fungsi tombol 3
         angka +="3";        
        display.setText(angka);
    }//GEN-LAST:event_bil3ActionPerformed

    private void pembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
         display.setText("/");
         angka="";
         pilih=4;
    }//GEN-LAST:event_pembagianActionPerformed

    private void perkuranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkuranganActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_perkuranganActionPerformed

    private void penjumlahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjumlahanActionPerformed
        String bilangan;
        // TODO add your handling code here:
     angka1=Double.parseDouble(angka);
     display.setText("+");
     angka="";
     pilih=1;
    }//GEN-LAST:event_penjumlahanActionPerformed

    private void bil7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil7ActionPerformed
        // fungsi tombol 7
        angka +="7";        
        display.setText(angka);
    }//GEN-LAST:event_bil7ActionPerformed

    private void bil9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil9ActionPerformed
        // fungsi tombol 9
         angka +="9";        
        display.setText(angka);
    }//GEN-LAST:event_bil9ActionPerformed

    private void bil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil4ActionPerformed
         // fungsi tombol 4
         angka +="4";        
        display.setText(angka);
    }//GEN-LAST:event_bil4ActionPerformed

    private void bil6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil6ActionPerformed
         // fungsi tombol 6
         angka +="6";        
        display.setText(angka);
    }//GEN-LAST:event_bil6ActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
         // fungsi tombol 1
         angka +="1";        
        display.setText(angka);
    }//GEN-LAST:event_bil1ActionPerformed

    private void bil0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil0ActionPerformed
         // fungsi tombol 0
         angka +="0";        
        display.setText(angka);
    }//GEN-LAST:event_bil0ActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
         // fungsi tombol =
       switch(pilih){
        case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
        case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
            default:
            break;
       }
    }//GEN-LAST:event_samadenganActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
       display.setText("");
       angka1=0;
       angka2=0;
       jumlah=0;
       angka="";
    }//GEN-LAST:event_clearActionPerformed

    private void perkalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkalianActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
         display.setText("x");
         angka="";
         pilih=3;

    }//GEN-LAST:event_perkalianActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_displayActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       int lenght= display.getText().length();
       int number= display.getText().length()-1;
       String store;
       
       if (lenght>0)
       {
           StringBuilder back = new StringBuilder(display.getText());
           back.deleteCharAt(number);
           store=back.toString();
           display.setText(store);
       }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorStandart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bil0;
    private javax.swing.JButton bil1;
    private javax.swing.JButton bil2;
    private javax.swing.JButton bil3;
    private javax.swing.JButton bil4;
    private javax.swing.JButton bil5;
    private javax.swing.JButton bil6;
    private javax.swing.JButton bil7;
    private javax.swing.JButton bil8;
    private javax.swing.JButton bil9;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField display;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton koma;
    private javax.swing.JButton pembagian;
    private javax.swing.JButton penjumlahan;
    private javax.swing.JButton perkalian;
    private javax.swing.JButton perkurangan;
    private javax.swing.JButton samadengan;
    // End of variables declaration//GEN-END:variables
}
